# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/custome_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Custom(object):
    def setupUi(self, Custom):
        Custom.setObjectName("Custom")
        Custom.resize(400, 417)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Custom.sizePolicy().hasHeightForWidth())
        Custom.setSizePolicy(sizePolicy)
        Custom.setMinimumSize(QtCore.QSize(400, 0))
        Custom.setMaximumSize(QtCore.QSize(400, 16777215))
        Custom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Custom)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Custom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Custom)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Custom)
        self.buttonBox.accepted.connect(Custom.accept) # type: ignore
        self.buttonBox.rejected.connect(Custom.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Custom)

    def retranslateUi(self, Custom):
        _translate = QtCore.QCoreApplication.translate
        Custom.setWindowTitle(_translate("Custom", "Dialog"))
